services:
  postgres:
    image: postgres:15.4-alpine3.18
    environment:
      - POSTGRES_DB=local_db
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_pass
      - PGPORT=5433
    ports:
      - "127.0.0.1:5433:5433"
    volumes:
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data:
